// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwhtckssabkxeeewcdyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aHRja3NzYWJreGVlZXdjZHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjkxNzQsImV4cCI6MjA2MzM0NTE3NH0.ZLEOcuOZlIBgQDPMSBMoezIlsWQjU0fT83ECZbym_bU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);